---
name: protols
description: A Simple LSP for proto3 protobuf files.
homepage: https://github.com/coder3101/protols
licenses:
  - MIT
languages:
  - Protobuf
categories:
  - LSP

source:
  id: pkg:cargo/protols@latest

bin:
  protols: cargo:protols
